pkg/phases/kubeadm.go
test/kind.config.yaml

k8s version 1.16 and later do not enable apps/v1beta1 and apps/v1beta2
by default. That causes some of the dependencies broken like pgo.
While waiting for those dependencies upgraded, we can make a workaround
by enable those features through runtime config.
Fixes #31

pkg/phases: set runtime config for k8s 1.16

---

manifests/node-local-dns.yml
pkg/phases/base/install.go
pkg/types/types.go
test/common.yml

Deploy NodeLocal DNSCache to improve cluster DNS performance.
This runs a DNS caching agent as a `DaemonSet` in each node.
Pods running in a node will first reach the local agent and only after in case of a cache miss reach out the DNS server deployed in the cluster.
In our case, we run CoreDNS deployed via kubeadm.
Reference:
https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

Add NodeLocal DNS cache

---

manifests/node-local-dns.yml
pkg/phases/base/install.go
pkg/types/types.go
test/common.yml

This PR aims to fix NodeLocalDNS.
It is still not tested.
I need to verify how the following values:
- `__PILLAR__CLUSTER__DNS__`
- `__PILLAR__UPSTREAM__SERVERS__`
are changed.
According to the documentation
> The following variables will be set by the node-cache images - k8s.gcr.io/k8s-dns-node-cache:1.15.6 or later. The values will be determined by reading the kube-dns configMap for custom Upstream server configuration.
`__PILLAR__CLUSTER__DNS__` - Upstream server for in-cluster queries.
`__PILLAR__UPSTREAM__SERVERS__` - Upstream servers for external queries.
But still not clear to me how.

Fix NodeLocalDNS

---

docs/admin-guide/vsphere.md
pkg/phases/konfigadm.go
pkg/provision/vsphere.go

See Issue https://github.com/flanksource/platform-cli/issues/241
Fixes runtime panics caused by referencing a missing `platform.CA` and updates provisioning instructions to include CA generation and config.

Fix panics caused by missing `ca` section

---

test/common.yaml

Fixes #263 with this commit:
https://github.com/flanksource/registry-creds/commit/cfe5cd0aaaa3cdf85edd70f7f6800d4fcb7d4beb

Bump registry-credentials version to 1.10.flanksource.2

---

.github/workflows/vsphere.yml
test/vsphere/e2e.sh
test/vsphere/vsphere.yaml

* switches the trigger event to cron-schedule trigger (**NOTE**: on the default branch workflow),
* aligns workflow with current kind workflow layout (binary step, testing matrix, etc.) to allow for future extension to more scenarios,
* disables minio e2e testing which was failing
closes #395

fix vSphere E2E test failures

---

pkg/platform/nsx.go

fix nsx nic tagging on terminated clusters skip-e2e 

---

manifests/kube-resource-report.yaml
pkg/types/types.go

Allows for the mapping of the labels used to track teams for use in the *Teams* tab.
Default labels are `team` and `owner` (i.e. `"team,owner"`), this PR adds a `kubeResourceReport.teamlabels` config key that allows a comma-separated list to be given to customise the default.
Applying these labels to pods will cause pods to be segmented according to the team specified in the value in the *Teams* tab:
e.g.
with the config
```yaml
kubeResourceReport:
teamlabels: team,owner,teams-label
```
Any pods labeled `team`, `owner` or `teams-label` will be indicated on the **Teams** tab.
<pre><font color="#8AE234"><i>philip@silent</i></font>:<font color="#729FCF"><i>/code/flanksource/karina-issue-435-kube-resource-report-map-team-labels</i></font>$ kubectl get pods --all-namespaces -l team …

add configurable mapping to teams label

---

README.md

Going through the `README.md` noticed that quickstarts links were returning `404`. 
This PR changes the link to the correct URL.
Signed-off-by: Tarun Khandelwal <khandelwaltarun32@live.com>

Fix quickstart links for Kind and vSphere

---

pkg/platform/platform.go
pkg/provision/kind.go

@moshloop Once this merges you should be able to update #506 to export CACHE_DIR=/runner/_work in order for the docker container to see them.

Kind cache configure

---

docs/admin-guide/provisioning/kind.md
manifests/dex.yaml
pkg/phases/platformoperator/install.go

Changes:
- fix: correct the default image tag of `platform-operator` and update to the latest version (`v0.5.2`)
- fix: change dex docker image repo to `ghcr.io/dexidp/dex`
- fix: update Kind Quickstart guide
What did I test:
- Built the latest binary from this branch
- Follow the updated Kind Quickstart guide from this branch
- Confirm all pods in the clusters are started up in healthy state
TODO:
- Will need to update the Kind Quickstart again once a new version is released after this PR is merged because the version in the example will not provision a healthy cluster.
Related PRs that can be closed after this is merged: https://github.com/flanksource/karina/pull/663 and https://github.com/flanksource/karina/pull/652
Fixes #651

Fix quickstart kind

---

.github/workflows/release.yml
.releaserc
docs/developer-guide/index.md

Implemented semantic-release job. This job can be triggered manually for now until we decide to have it run on every commit pushed to master. With this configuration we will have:
- Automatically determine the next version bump of the release based on commits from the last version
- Create tag automatically
- Create GitHub release with correct assets and changelog generated from commits
- None
- Thoroughly tested the workflow in my fork repo. Example of this workflow run: https://github.com/tobernguyen/karina/actions/runs/557301880
- Releases were created with this workflow: https://github.com/tobernguyen/karina/releases
- Merge this PR
- Go to Repo -> Actions -> Create Release -> Run workflow -> Run workflow from master
Closes …

Implement semantic-release

---

cmd/cleanup-jobs.go
main.go

Proposal solution for issue #458.
Creates a new command (expecting the `--namespace` as a flag) to remove all jobs with a state not equal to "_succeeded_" on the provided namespace.
I didn't test it through the **karina** commands, but I did some tests of the `BatchV1().Jobs` in an **OpenShift/Kubernetes** environment.
https://github.com/flanksource/karina/issues/458

feat: Remove all failed jobs in a given namespace

---

.github/workflows/release.yml
pkg/phases/argorollouts/test.go

Fixes https://github.com/flanksource/karina/issues/698 and add some enhancements:
- Only build and push docker images when there is a new version released from semantic-release.
- Always build docs as we might want to update docs even there are no functional changes.
- None
- Trigger "Create release" workflow
- It created a new release on my forked repo
- It pushes docker image with expected tags: latest, snapshot, and the new-released-tag to my dockerhub repo: https://hub.docker.com/repository/docker/tobernguyen/karina

ci: fix create-release not pushing docker tag

---

manifests/monitoring/alertmanager-rules.yaml.raw

Adds a default alert for iff a container requests too large a percentage of host CPU
NA
- [ X ] No
Verified rules in PromQL browser
Deployed packed ruleset to test cluster
Fixes: #705

Container too large alert

---

manifests/monitoring/alertmanager-rules.yaml.raw

Add an alert to warn if container requests exceed actual utilisation by an order of magnitude
NA
- [ X ] No
Verified Prometheus logic with prometheus UI
Deployed prometheus rules to test cluster
```
DEBU[0110] Applying monitoring/alertmanager-rules.yaml.raw
INFO[0111] prometheusrules/monitoring/prometheus-k8s-rules configured
```
Fixes #704 (set to 10% rather than 5%)

Overprovision alert

---

manifests/canary-checker-alerts.yaml.raw
pkg/phases/canary/deploy.go

Deploy default prometheus alerts that report the state of the canary-checker canaries
- [ X ] No
```
.bin/karina deploy all -c test/monitoring.yaml
kubectl get prometheusrules --all-namespaces
NAMESPACE         NAME                            AGE
cert-manager      prometheus-cert-manager-rules   67m
monitoring        kubernetes-rules                59m
monitoring        namespace-k8s-rules             59m
monitoring        postgres-rules                  59m
monitoring        prometheus-k8s-rules            59m
platform-system   canary-checker-rules            59m
```
Fixes #703

feat: Add default alerts to Canary-Checker deployment

---

manifests/opa-gatekeeper-monitoring.yaml.raw
pkg/phases/opa/install.go

Add default alerts to notify if gatekeeper enforcements are active
NA
- [ X ] No
Validated pod/servicemonitor config on test cluster
Validated alert logic in PromQL
NA

feat: add default gatekeeper alerts

---

manifests/flux-monitor.yaml

Fix the default flux alert config by moving away from serviceMonitors in favour of podMonitors.  The kommons builder that currently generates the flux service does not have any hooks to add the necessary labels to the service for serviceMonitor to detect
NA
- [ X ] No
Deployed manifests/flux-monitor.yaml to running cluster
Verified flux targets came up in prometheus and flux alert metrics were available in promQL browser
NA

fix: Use podmonitor rather that servicemonitor for flux scraping

---

.github/workflows/kind.yml
.github/workflows/release.yml
.github/workflows/selfhosted.yml
.github/workflows/upgrade.yml
.github/workflows/vsphere.yml

Bump build tools version to ensure go 1.16 is available in the buildenv
NA
- [ X ] No
NA, changes to workflows will be checked in workflow results
Fixes #720

chore: bump build env to go1.16 based image

---

.github/workflows/kind.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/selfhosted.yml
.github/workflows/upgrade.yml
.github/workflows/vsphere.yml
.gitignore
Makefile
docs/developer-guide/index.md
docs/developer-guide/make-targets.md
go.mod
manifests/static.go
pkg/phases/monitoring/monitoring.go
pkg/phases/nginx/install.go
pkg/phases/opa/install.go
pkg/platform/platform.go
scripts/golint.sh

Package static content with the go:embed directive rather than esc
#720 
- [ X ] No
No compatibility breaks, but does bump the required version of go to 1.16.  Please update dev environments accordingly
Checked Make functions correctly
Checked 'deploy opa' on a kind cluster - opa target uses both static resources by name and by directory.
Fixes #695

Switch from ESC to Go embed

---

manifests/monitoring/unmanaged/alertmanager-rules.yaml.raw

Two separate files both contain the definition for a prometheus ruleset named `prometheus-k8s-rules`.  Renamed the ruleset in the one file to prevent the other being overridden during deployment
NA
- [ X ] No
NA
Fixes #733

fix: rename conflicting prometheus ruleset

---

manifests/opa-gatekeeper-monitoring.yaml.raw

Relax a changed label for the podmonitor responsible for picking up violation rules
NA
- [ X ] No
Verified podmonitor config in running cluster (Violationcount alert now firing)
N/A

fix: update gatekeeper-audit podmonitor labelselector

---

docs/reference/config.md
manifests/filebeat.yaml
pkg/types/types.go

Add an ssl option to filebeat config
NA
- [ X ] No
tested with elastic SUITE:
```
output.elasticsearch:
hosts: ['${ELASTIC_URL}']
username: ${ELASTIC_USERNAME}
password: ${ELASTIC_PASSWORD}
protocol: https
ssl: '{"supported_protocols":["TLS1.2","TLS1.3"],"verification_mode":"none"}'
index: "filebeat-infra-%{[agent.version]}-%{+yyyy.MM.dd}"
```
Replaces #756

Filebeat ssl config

---

cmd/common.go
cmd/common_test.go
test/fixtures/unrecognized-fields.yaml

Fixes: #700. Causes Karina to fail when encountering unrecognized fields.Not sure if this should be a warn and continue anyway though as it is currently a breaking change.

feat: fail on unrecognized config fields

---

test/test.sh
test/upgrade.sh

Change test logic to use local make output instead of (presumably) stable binary from path
NA
- [ X ] No
reran test.sh locally, verified local bin was used for testing
NA

test: use local karina before path karina when testing

---

pkg/phases/elasticsearch/install.go

Elasticsearch install fails when persistence is not set, due to the  template encountering a nil value rather than a bool.  Set a default value to prevent this
NA
- [ X ] No
```
karina deploy -c test/config.yaml elasticsearch
INFO[0000] Elasticsearch/eck/logs (created) 
INFO[0000] Kibana/eck/logs (created) 
INFO[0000] Ingress/eck/logs-ing (created) 
INFO[0000] Ingress/eck/kibana-ing (created) 
```
on kind cluster with no persistence set in config
NA

fix: set default for elasticsearch persistence

---

manifests/monitoring/alertmanager-rules.yaml.raw

Adds a record of the weekly average log voume, and an alert if the current volume exceeds this by a factor of 2
NA
- [ X ] No
Expression logic verified in PromQL
NA

feat: add logvolume alert to default prometheus rules

---

go.mod
go.sum
manifests/crd/postgresql-db.yaml
manifests/template/postgresql-db.yaml.raw
manifests/upstream/postgresql-db/crd/kustomization.yaml
manifests/upstream/postgresql-db/template/kustomization.yaml
pkg/client/postgres/tasks.go
pkg/phases/postgresoperator/test.go
test/cicd.yaml
test/postgres.yaml

TODO:
- https://github.com/flanksource/template-operator/pull/37
- https://github.com/flanksource/template-operator-library/pull/19
- Build the binary with `make`
- `karina deploy template-operator`
- `karina deploy postgres-operator`
- Deploy 2 PostgresqlDB objects:
`db.yaml`: v1 of PostgresqlDB which disables restic backup by default
```
apiVersion: db.flanksource.com/v1
kind: PostgresqlDB
metadata:
name: test-db-v1
namespace: postgres-operator
spec:
backup:
bucket: test-pg-backup
schedule: "*/5 * * * *"
replicas: 1
storage:
size: 1Gi
parameters:
archive_mode: "on"
archive_timeout: 60s
log_destination: stderr
max_connections: "600"
shared_buffers: 2048MB
```
`db-v2.yaml` v2 of PostgresqlDB which enables restic backup by default
```
apiVersion: db.flanksource.com/v2
kind: …
```

fix: make restic backup optional and backwards compatible

---

manifests/harbor/core.yaml
manifests/harbor/exporter.yaml
manifests/monitoring/dashboards/grafana-dashboard-harbor.json.raw
pkg/phases/harbor/install.go
pkg/platform/platform.go
test/patch1.yaml

- Updated the harbor exporter to the new official image in 2.2, based on the helm charts (here)[https://github.com/goharbor/harbor-helm/tree/v1.6.1/templates/exporter]
- Updated core pod to expose metrics and added core service monitor
- Imported grafana dashboard from (here)[https://grafana.com/grafana/dashboards/14075]
NA
made bin
deployed to kind, initial setup with `test/test.sh harbor2`
additionally ran `karina deploy monitoring -c test/monitoring.yaml`
verified 3 working servicemonitors in prometheus UI
verified grafana dashboard mostly working.
Some of the fields in the registry/core metrics are not being picked up, since they have not been triggered yet
Fixes #853

Harbor metrics

---

manifests/harbor/core.yaml
manifests/harbor/trivy.yaml

Add certificates, volumemounts and volume for harbor-trivy
This should be the actual fix for #854 - tracing through the trivy logic leads to https://github.com/aquasecurity/fanal/blob/main/image/image.go#L70 which shows trivy attempts to read the image from a local docker registry via socket, from podman and then from a remote registry.  The third method is the desired usecase in harbor and the error regarding connection to a docker socket is misleading.  The error regarding unknown CA is the actual error, which is addressed here.
NA
Applied to kind cluster with harbor2.yaml deployed.
before patch, connection from trivy to harbor core fails:
```
sh-4.4$ curl https://harbor-core.harbor.svc.cluster.local.:443/v2/
curl: (60) SSL certificate problem: unable to get local issuer certificate …
```

Setup cert-manager certificates for harbor-trivy

---

.github/workflows/kind.yml
manifests/nginx.yaml

Fixes errors like: `Translation failed: invalid ingress spec: service "uat/clearbank" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

Add IngressClass for nginx ingress

---

.github/workflows/kind.yml
test/hosted-tests.yaml
test/minimal.yaml
test/vsphere-harbor.yaml

Patch the self-hosted tests to use calico and minio from harbor to prevent docker.io rate limit issues

ci: use harbor for core images

---

pkg/ca/ca.go

Check if password is empty rather than key when chosing betweeen decode and decrypt

fix: correctly choose between decode and decrypt

---

manifests/packetbeat.yaml

Removes `/etc/kubernetes/kubelet.conf` from packetbeat

fix: do not mount kubelet.conf in packetbeat pods

---

manifests/eck.yaml

The cert in the eck is a dummy to trigger deletion if eck is switched to disabled.  It is often a failure point in deployments that use elasticsearch, with `the object has been modified` errors

chore: remove dummy cert from eck manifest

---

manifests/packetbeat.yaml

Change packetbeat pod dns policy to be able to use svc addresses
NA
NA

feat: set packetbeat dns policy

---

cmd/seal.go
cmd/unseal.go
go.mod
go.sum
main.go

Adds support for generating sealedsecrets using kubeseal
Replaced `kubeseal` with `karina seal` in calls to create sealedsecrets
Fixes: #645

feat: add seal command for kubeseal

---

manifests/external-dns.yaml

Fix rbac config that prevents external-dns from starting correctly
Inserted updated clusterrole into faulty cluster

fix: correct external-dns rbac

---

pkg/phases/monitoring/monitoring.go

Adding a missing string conversion call on dynamic grafana dashboard names
deployed monitoring to test cluster

fix: make built-in dashboard names DNS1192 compatible

---

manifests/elasticsearch.yaml

Elastic operator fails to start looking for it
Deployed in kind and BCB clusters

fix: create elasic-webhook-server certificate

---

pkg/phases/certmanager/install.go
pkg/types/types.go

In cases where complex clusterissuer specs need to be constructed outside of karina and managed via kustomise, the current behaviour creates conflicting issuer configs.  Add a config flag to prevent an ingress clusterissuer being created in such scenarios

feat: add flag to prevent ingress cluster issuer being created

---

manifests/eck.yaml
manifests/elasticsearch.yaml

Should be deployed in `eck.yaml`, not `elasticsearch.yaml`

fix: deploy eck webhook certificate with eck operator

---

manifests/dex.cfg
manifests/dex.yaml
pkg/phases/dex/install.go
pkg/types/types.go

Adds gitlab connector config to dex configmap, along with requisite karinaConfig entries and secret creation in dex install phase.
NA

feat: add gitlab connector to dex

---

manifests/dex.cfg

Fixes errors like 
```
time=2021-11-18T07:31:00Z level=fatal msg=Failed to deploy bootstrap: install: failed to template configmap: error executing template issuer: https://dex.{{.domain}}: template: :74:12: executing "" at <index .dex.gitlab.groups>: error calling index: index of untyped nil
```
Tested in kind

fix: correct index use in dex config

---

manifests/external-dns.yaml

add ingress.networking.k8s.io to resource that external-dns can access

chore: add new ingress apigroup to external dns rbac

---

pkg/phases/monitoring/monitoring.go

Reverse currently incorrect logic to determine whether the monitoring/unmanaged alert rules should be installed on a cluster
NA

fix: do not install unmanaged rules on managed clusters

---

pkg/phases/monitoring/monitoring.go

The specs and dashboards are excluded if the function returns true
Tested in kind

fix: correct inverted logic around managed clusters

---

manifests/monitoring/alertmanager-rules.yaml.raw

Restricts CPU and Memory oversubscribed warnings to the cases when the CPU/memory load respectively is greater than 60%
Tested suing BCB legacy staging prometheus queries

fix: only alert on oversubscribed nodes when they are under load

---

manifests/canary-checker.yaml
manifests/flux-v2.yaml
manifests/monitoring/kube-prometheus.yaml

Adds an annotation to pods that are usually deployed with an emptyDir to allow them to relocated by cluster autoscalers
NA

Autoscaler compatibility

---

manifests/monitoring/nginx-alerts.yaml.raw
manifests/nginx.yaml
pkg/phases/nginx/install.go

Adds a new manifest and corresponding install phase actions to deploy alerts specific to the nginx ingress controller
NA

Feat: add alerting hook for nginx specific alerts

---

manifests/logs-exporter.yaml
manifests/monitoring/kube-state-metrics.yaml
manifests/monitoring/node-exporter.yaml

Older kube-rbac-proxy images use the deprecated authentication/v1beta api call rather than v1.  Newer image version are needed for kubernetes 1.22
NA
Verified Prometheus is able scrape node-exporter pods with the new sidecar image

chore: bump kube-rbac-proxy versions

---

manifests/sealed-secrets.yaml

sealed secrets controller is no longer hosted on quay and attempting to access to the old url gives a 403 error.
update manifest to use the new default registry at docker.io
NA

chore: update default registry for sealed-secrets-controller

---

config/operator/default/webhookcainjection_patch.yaml
manifests/kpack.yaml
manifests/opa-kubemgmt.yaml
manifests/tekton.yaml

Update deprecated beta1 webhook apis to v1
NA

chore: update webhook apiVersion for 1.22

---

manifests/monitoring/grafana-operator.yaml
manifests/monitoring/kube-state-metrics.yaml

Bump kube-state-metrics version for 1.22 compatibility - older version has lots of failed calls to deprecated api endpoints
Bump grafana and grafana operator versions - hitting a bug in some environments where dashboards are constantly being reloaded because of a comms issue between the two
NA

Version bumps

---

manifests/monitoring/kube-state-metrics.yaml

Kube state metrics project is now part of kubernetes and is found in a different image registry
NA

fix: update kube-state-metric registry location

---

manifests/monitoring/alertmanager-rules.yaml.raw

Updated NodeFilesystemSpaceFillingUp rule to adequate the rule from  Prometheus operator's node exporter prometheus rule
https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/nodeExporter-prometheusRule.yaml#L15

fix(node-exporter-rule): updated NodeFilesystemSpaceFillingUp

---

manifests/eck.yaml

Add an rbac entry for the new leadership election mechanism in eck 2.3
NA
edited rbac in cluster, eck operator stopped error loop

fix: add rbac needed for eck 2.3

---

manifests/canary-checker-monitoring.yaml.raw

exported_endpoint isn't a valid Prometheus label, so use name instead

fix: use name in canary alert messages

---

.github/workflows/release.yml

This allows them to be added to the release manually if the automatic upload fails

fix: upload release artifacts to CI run too

---

pkg/phases/flux/fluxv2.go

This allows us to deploy from upstream without Karina deleting it after the fact. With things moving out of Karina, this should probably be the standard approach

feat: do not delete flux when disabled

---

pkg/phases/canary/deploy.go

This allows us to deploy from upstream without Karina deleting it after the fact

feat: do not delete canary-checker when disabled

---

pkg/phases/sealedsecrets/install.go

This ensures that we can replace it with upstream Helm chart without Karina deleting things

feat: do not delete sealed-secrets on disable

---

pkg/phases/nginx/install.go

Don't delete nginx when karina releases ownership of it, to allow seamless switchover  to helm owned resources

fix: orphan nginx instead of deleting
