- manifests/monitoring/kube-prometheus.yml
> Configure prometheus and alert manager to provide correct URLs in alerts

- .circleci/config.yml
- cmd/backup.go
- cmd/deploy.go
- cmd/test.go
- go.mod
- main.go
- manifests/cert-manager-deploy.yml
- pkg/k8s/client.go
- pkg/k8s/tests.go
- pkg/k8s/types.go
- pkg/phases/stubs/install.go
- pkg/phases/velero/install.go
- pkg/phases/velero/test.go
- pkg/phases/velero/types.go
- pkg/platform/platform.go
- pkg/types/types.go
- test/common.yml
- test/e2e.sh
> Add velero support

- manifests/monitoring/dashboards/cluster.json
- pkg/phases/monitoring/monitoring.go
Replace it at deploy time using domain configured URL
> Add alert manager URL as variable in grafana template.

- manifests/monitoring/alertmanager-rules.yml.raw
- manifests/monitoring/dashboards/etcd.json
- manifests/monitoring/kube-prometheus.yml
- manifests/monitoring/service-monitors.yml
Add etcd service discovery and service monitor.
Add grafana dashboard for etcd
Add etcd alert rules
Fix prometheus routePath which is wrongly generated when setting externalURL
> Etcd monitoring #63

- manifests/monitoring/kube-prometheus.yaml
> Both Prometheus and Thanos datasources on observability mode

- cmd/test.go
- pkg/phases/monitoring/test.go
> Added Prometheus tests

- manifests/monitoring/dashboards/alerts.json.raw
- manifests/monitoring/dashboards/cluster-dash.json.raw
> Added Alertmanager dashboard and critical alerts panel to main dashboard

- pkg/phases/dex/test.go
- pkg/types/types.go
- test/common.yaml
> Add test authentication credentials for ldap

- .circleci/config.yml
- cmd/db.go
- docs/admin-guide/administration/consul.md
- docs/admin-guide/administration/databases.md
- mkdocs.yml
- pkg/api/postgres/cluster_config.go
- pkg/phases/harbor/install.go
- pkg/phases/postgresoperator/tasks.go
- pkg/phases/postgresoperator/test.go
- pkg/platform/platform.go
- pkg/types/types.go
- test/common.yaml
> Issue 261 postgres operator refactoring

- manifests/harbor-exporter.yaml
- pkg/phases/harbor/install.go
> Add harbor exporter

- manifests/monitoring/karma.yaml
- manifests/monitoring/kube-prometheus.yaml
- pkg/phases/monitoring/monitoring.go
- pkg/types/types.go
> add karma alerting dashboard

- .github/workflows/kind-image.yml
- cmd/docker-images.go
- go.sum
- pkg/k8s/client.go
- pkg/phases/certmanager/install.go
- pkg/phases/harbor/install.go
- pkg/phases/quack/install.go
- pkg/phases/sealedsecrets/install.go
- pkg/platform/platform.go
- scripts/generate_kind_image.sh
> Add script to build kind node-image

- pkg/k8s/client.go
> Health check should not include pods with priority < 0

- manifests/monitoring/karma.yaml
- pkg/phases/monitoring/monitoring.go
- pkg/types/types.go
> Fix CORS issues when silencing alerts in karma

- cmd/test.go
- pkg/k8s/client.go
- pkg/test/template.go
- test/fixtures/template-test.yaml
- test/minimal.yaml
- test/templatePatch.yaml
- test/test.sh
> Add templating to patches

- manifests/monitoring/dashboards/summary-pvc.json.raw
> Add summary pvc dashboard

- manifests/monitoring/thanos-config.yaml
- test/monitoring.yaml
> Update thanos to 0.13.0

- pkg/phases/opa/install.go
> Ensure ConstraintTemplate exists before utilising

- cmd/harbor.go
- go.mod
- pkg/phases/harbor/client.go
- pkg/phases/harbor/operations.go
> Karina harbor cmds

- pkg/provision/rolling.go
error out if rolling fails to update all nodes, and tighten node selection criteria during roll
> Rolling failure report

- pkg/phases/dex/install.go
> bump dex version

- go.mod
- go.sum
- pkg/phases/minio/test.go
- pkg/phases/monitoring/test.go
- pkg/phases/opa/test.go
- pkg/test/template.go
For the tests not covered by https://github.com/flanksource/kommons/pull/14
> Make test name unique

- .github/pull_request_template.md
- .github/semantic.yml
- README.md
- test/linter.yaml
Add some helpful default rules for Probot Semantic Pull Request
Relate to https://github.com/flanksource/karina/issues/673
Closes https://github.com/flanksource/karina/issues/668
> Add probot semantic rule and PR template

- pkg/phases/elasticsearch/install.go
Fix some elasticsearch deployment issues that are likely causing issues in the CI
NA
- [ X ] No
Verify via CI tests
Related: #706 
Fixes #696
> Fixes to elasticsearch deployment routine

- docs/admin-guide/opa.md
- pkg/constants/const.go
Add tekton to gatekeeper whitelist
NA
- [ X ] No
NA
NA
> Add tekton to gatekeeper whitelist

- Makefile
- docs/developer-guide/index.md
Misc fixes that were missed in the update to go embed
NA
- [ X ] No
NA
Fixes #731
> fix: make pack / go-embed issues

- .github/workflows/kind.yml
- README.md
> Create CI pipeline badge matrix

- pkg/phases/certmanager/install.go
Fixes the Letsencrypt issuer to work with Route53 DNS challenges
> Fix: Letsencrypt issuer

- manifests/monitoring/alertmanager-rules.yaml.raw
Add CPU and memory based alerts for node status to default prometheus rules
NA
- [ X ] No
Verified expressions in PromQL browser
Fixes #765
> feat: Add various CPU usage alerts to default prometheus rules

- .github/workflows/vsphere.yml
- test/vsphere/e2e.sh
Initial work so that I can run tests and work on the failures.
> Setup vSphere CI

- manifests/harbor/chartmuseum.yaml
- manifests/harbor/clair.yaml
- manifests/harbor/core.yaml
- manifests/harbor/exporter.yaml
- manifests/harbor/jobservice.yaml
- manifests/harbor/portal.yaml
- manifests/harbor/redis.yaml
- manifests/harbor/registry.yaml
- test/patch1.yaml
> chore: add resource requests/limits to harbor

- manifests/template-operator.yaml
Increase resource limits for template operator deployments
NA
- [ X ] No
NA
NA
> feat: Increase template operator resource limits

- .gitignore
- cmd/terminate.go
- main.go
- pkg/provision/terminate.go
Signed-off-by: Tarun Khandelwal <tarun@flanksource.com>
Removed the cleanup cmd moved the cmd to terminate
> feat: remove cleanup alias for karina terminate

- docs/admin-guide/provisioning/kind.md
- docs/admin-guide/troubleshooting.md
> docs: troubleshooting review

- test/harbor2.yaml
Karina kind isn't playing nicely for me, so PR with a test bump to see if there are any issues in CI
Fixes: #713
> chore: bump harbor version to 2.2.0

- manifests/platform-operator.yaml
> fix: set default platform-operator version

- docs/operators/postgres.md
Added documentation to hard reset a failed postgres cluster
NA
No
Steps recorded from process followed at customer site
NA
> Postgres docs

- manifests/monitoring/alertmanager-rules.yaml.raw
Adjust alert description
Fixes #857
> fix: fix logvolume alert description

- .github/workflows/kind.yml
- .github/workflows/lint.yml
- Makefile
- test/linter/main.go
Signed-off-by: Tarun Khandelwal <tarun@flanksource.com>
Check all the manifests and see if there is any duplicate keys found the identification key is in the form `<kind>-<name>-<namespace>` or `<kind>-<name>` in case namespace is not present
Just run the linter file directly `go run test/linter/main.go`
> chore: Lint duplicate manifests

- pkg/phases/templateoperator/install.go
Display errors if namespace-configurator deployment/removal fails
> fix: unsquash namespace configurator deployment error message

- manifests/dex.cfg
- manifests/dex.yaml
- pkg/phases/dex/install.go
- pkg/types/types.go
Adds Google OIDC support to Dex
Deployyed
> feat: add Google connector to Dex

- manifests/filebeat.yaml
> feat: ingest Kubernetes audit logs

- manifests/filebeat.yaml
- manifests/nginx.yaml
- pkg/phases/filebeat/install.go
- pkg/phases/nginx/install.go
- pkg/types/types.go
- test/elastic.yaml
Enables access logs in nginx ingresses and sets up hints for filebeat nginx module
NA 
Fixes #809
> Nginx filebeat config

- manifests/filebeat.yaml
Fix duplicate key in filebeat annotation
> fix: filebeat annotation

- manifests/filebeat.yaml
Fix incorrect indentation in spec 
built and successfully deployed filebeat
> fix: filebeat annotation indentation

- pkg/provision/kind.go
> fix: change conntrack.maxPerCore to 0

- .github/workflows/kind.yml
- Makefile
**What I did:** Fixed the fetch depth in GitHub workflow's checkout action, so that tags can be retrieved 
Checked  the Workflow output's in the fork 
#896 review-requested: @moshloop
> fix: karina version includes only timestamp #896

- manifests/crd/konfig-manager.yaml
- manifests/kpack.yaml
- test/konfig-manager.yaml
> chore: bump konfig-manager to v0.8.0

- manifests/monitoring/dashboards/namespaces.json.raw
- manifests/monitoring/dashboards/summary-nodes.json.raw
- manifests/monitoring/dashboards/summary-pvc.json.raw
- manifests/monitoring/grafana-operator.yaml
> fix: upgrade grafana to 8.x, fix summary dashboards datasource

- manifests/monitoring/pushgateway.yaml
- manifests/monitoring/service-monitors.yaml
- pkg/phases/monitoring/monitoring.go
- pkg/types/types.go
> feat: deploy push gateway

- manifests/canary-checker.yaml
- manifests/crd/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
- manifests/upstream/canary-checker/crd/kustomization.yaml
- manifests/upstream/template-operator/base/kustomization.yaml
- manifests/upstream/template-operator/crd/kustomization.yaml
Updated canary-checker and template-operator manifests
> chore: update template-operator and canary-checker

- manifests/nginx.yaml
Upgrade nginx ingress version to 0.48.1
Tested in kind
> chore: upgrade nginx ingress version

- manifests/dex.cfg
- manifests/dex.yaml
- pkg/phases/dex/install.go
- pkg/types/types.go
- Add github oauth struct to dex struct
- more closely align templating logic with file layout
- add github secret creation to dex install
> feat: add github auth config to dex

- manifests/canary-checker.yaml
- manifests/crd/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
- manifests/upstream/canary-checker/crd/kustomization.yaml
- pkg/platform/platform.go
- test/linter/main.go
> Bump canary checker

- cmd/seal.go
> fix: error checks on seal path logic

- manifests/modsecurity-filebeat.yaml
- pkg/phases/nginx/install.go
- pkg/types/types.go
Adds JSON parsing and index configuration. This does break showing the message in Kibana. @moshloop do you want me to add a processor to construct a readable message field?
Deployed into canary cluster. Visible in Kibana
Fixes: #967, #968
> Modsecurity Fixes

- manifests/monitoring/dashboards/kubelet.json
- manifests/monitoring/dashboards/kubernetes-cluster-rev2.json
- manifests/monitoring/dashboards/nginx-ingress-controller-rev1.json.raw
These dashboards were not working correctly on the new instance. Played around with the queries and when checking everything was working pasted the exported file in the json
Verified the working results on the grafana dashboard.
Still need to checkout the certmanager dashboard
> chore: fix json for grafana dashboards

- manifests/dex.cfg
- pkg/types/types.go
adds an extra configuration field for gitlab dex conenctions
NA
> feat: add gitlab auth url to config

- manifests/cert-manager.yaml
- manifests/crd/cert-manager.yaml
- manifests/upstream/cert-manager/base/kustomization.yaml
- manifests/upstream/cert-manager/crd/kustomization.yaml
- pkg/types/default.go
> chore(cert-manager): cert-manager version bump (v1.6.1)

- README.md
> docs: adds slack link

- manifests/crd/canary-checker.yaml
- manifests/external-dns.yaml
- manifests/upstream/canary-checker/crd/kustomization.yaml
- manifests/upstream/external-dns/base/kustomization.yaml
updated bundled crd version for canary checker and external-dns
> chore: update bundled upstream manifests

- manifests/dex.cfg
- pkg/types/types.go
Add gitlab url config to dex spec
> Dex gitlab url

- manifests/canary-checker.yaml
- manifests/crd/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
- manifests/upstream/canary-checker/crd/kustomization.yaml
Bumps canary-checker to v0.38.67
> chore: bump canary-checker version

- pkg/phases/monitoring/monitoring.go
> fix: adjust monitoring go formatting

- pkg/phases/monitoring/monitoring.go
More incorrect logic that needed inverting
> fix: do not install unmanaged dashboards/alert rules on managed clusters

- manifests/eck.yaml
- manifests/upstream/eck/base/kustomization.yaml
> fix: use config version for eck image tag

- .github/workflows/nightly_quarantine.yml
remove copy pasted config pointing a gate job that is not required on nightly runs
Verifying with submission
> ci: remove incorrect job dependency

- go.mod
- go.sum
- manifests/nginx.yaml
- pkg/types/default.go
- pkg/types/types.go
Adds support for the ingress v1 compatbile nginx controller + requisite cli options and ingressClass objects
NA
> feat: update nginx manifests for ingress v1

- manifests/Makefile
- manifests/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
The typo resulted in the config being ignored
> fix: use configured storageclass instead of default

- manifests/nginx.yaml
Fix cli argument generation for nginx pod based on default/non-default flag
N/A
> fix: nginxv1 cli generation

- manifests/canary-checker.yaml
- manifests/monitoring/grafana-operator.yaml
- manifests/upstream/canary-checker/base/servicemonitor.yaml
- manifests/upstream/canary-checker/helm/chart.yaml
- manifests/upstream/monitoring/grafana-operator/base/kustomization.yaml
Update some generated manifests
NA
> Manifest updates

- manifests/monitoring/kube-prometheus.yaml
- manifests/monitoring/prometheus-adapter.yaml
Add more autoscaler compaibility annotations to pods that declare emptydirs
NA
> Autoscaler compatibility

- manifests/canary-checker.yaml
- manifests/crd/canary-checker.yaml
- manifests/upstream/canary-checker/helm/chart.yaml
Update canary checker to latest version, pull updated rbac and crd
NA
> chore: update canary-checker crd

- pkg/phases/nginx/install.go
Fix bug in nginx apply logic
NA
Manual install working now
> fix: bug in nginx deploy logic

- Dockerfile
Update missed dependency update in docker image
NA
> fix: update go version in dockerfile to 1.18

- manifests/crd/grafana-operator.yaml
- manifests/upstream/grafana-operator/crd/kustomization.yaml
- manifests/upstream/monitoring/grafana-operator/base/kustomization.yaml
Fixes: #1029 as the operator is already in upstream
> fix: update grafana operator to 4.4.1

- manifests/canary-checker.yaml
- manifests/crd/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
- manifests/upstream/canary-checker/helm/chart.yaml
- manifests/upstream/canary-checker/helm/values.yaml
- pkg/types/types.go
> fix(canary-checker): upgrade to v0.38.183

- manifests/Makefile
- manifests/canary-checker.yaml
- manifests/upstream/canary-checker/base/kustomization.yaml
- pkg/phases/elasticsearch/install.go
- pkg/types/types.go
you can use the following to disable persistence:
```yaml
canaryChecker:
persistence:
disabled: true
```
Backwards compatible as it is enabled by default
> feat(canary-checker): allow persistence to be disabled

- .github/workflows/release.yml
> fix: correct release upload actions

- pkg/phases/eck/install.go
This ensures that we can replace it with upstream Helm chart without Karina deleting things
> feat: do not delete eck on disable

- pkg/phases/crds/install.go
> fix: add the ability to disable cert manager crds
